$(document).ready(function(){
  var hide = function(){
    $('#retiredExpand').hide();
    $('#depthExpand').hide()
    $('#playoffExpand').hide();
    $('#mascotExpand').hide();
  }
  hide();
  $('.retired').hover(function(){
    $('#retiredExpand').show(600);
    $('#depthExpand').hide(400);
    $('#mascotExpand').hide(400);
    $('#playoffExpand').hide(400);
  })
  $('.depth').hover(function(){
    $('#depthExpand').show(600);
    $('#retiredExpand').hide(400);
    $('#mascotExpand').hide(400);
    $('#playoffExpand').hide(400);
  })
  $('.mascot').hover(function(){
    $('#mascotExpand').show(600);
    $('#depthExpand').hide(400);
    $('#retiredExpand').hide(400);
    $('#playoffExpand').hide(400);
  })
  $('.playoff').hover(function(){
    $('#playoffExpand').show(600);
    $('#depthExpand').hide(400);
    $('#retiredExpand').hide(400);
    $('#mascotExpand').hide(400);
  })

$('.content').hover(function(){
hide();
})
$('body').hover(function(){
  hide();
})
$('a').click(function(){
  hide();
})

})
